server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 50m;

    resolver 127.0.0.11 valid=30s;

    location /api/ {
        set $backend http://backend:8000;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
