services:
  qdrant:
    image: akritiyadav/scholarrag:qdrant-v1
    ports:
      - "6333:6333"
    restart: always

  backend:
    image: akritiyadav/scholarrag:backend-v12
    ports:
      - "8000:8000"
    volumes:
      - ./users.db:/app/data/users.db
    env_file:
      - ./.env
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_SVC_PORT=6333
      - DB_PATH=/app/data/users.db
    depends_on:
      - qdrant
    restart: always

  frontend:
    image: akritiyadav/scholarrag:frontend-v1
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
